version: '3.9'

services:

  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medev-planify-backend
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${APP_PORT}
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db